### ISSUE TITLE
bugfix: warn/stop when allocation exceeds the randomization rule

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/inferference#13]
User can currently specify an allocation greater than the randomization rule. 

This should probably return a warning (or maybe even an error).

I suggest to have a default to stop and return an error, but the user can specify an argument for the program to run and complete without issues if they so choose.

**Comment by bsaul** [comment]
I'm not sure what you mean by randomization rule. Do you mean the optional 'r' argument in logit_integrand?

**Comment by BarkleyBG** [comment]
I mean the argument `randomization = 2/3` as used in the vaccine example in the intro vignette

**Comment by bsaul** [comment]
The allocations can be in (0,1) irregardless of the randomization.

**Comment by bsaul** [comment]
Closing as I don't think this is a problem.
