### ISSUE TITLE
Remove stale develop branch?

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/inferference#18]
In the interest of starting new development on this package, is it time to kill the stale develop branch with my terrible commits on it?

I don't think anyone is downstream from it, so can we kill it quietly? Or, keep those commits in a new branch, and start the Develop branch fresh from Master.

Relevant information that I'm choosing to ignore right now: [how to git flowchart](http://justinhileman.info/article/git-pretty/)

**Comment by bsaul** [comment]
I think we kill it quietly and start anew.

**Comment by BarkleyBG** [comment]
OK, i'll work from current master head and PR to develop whenever you create it

**Comment by bsaul** [comment]
Just added a `dev` branch
