### ISSUE TITLE
Estimated Random Effect Variance of 0

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/inferference#4]
When the GLMER model estimated variance of the random effect is 0, calculation of robust variance can be impossible due to non-invertible V matrix. Package should be able to caution user that the data does not allow for this option, instead of quitting and returning an error. Perhaps use a try() function and return description of the issue.

I may have described two separate issues with the code; I hope not.

**Comment by bsaul** [comment]
Resolved by latest commit: https://github.com/bsaul/inferference/commit/8ce712d5b5924515c6fe975a641df8e6c579d030
